/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as AppRouteImport } from './routes/app/route'
import { Route as authRouteImport } from './routes/(auth)/route'
import { Route as IndexImport } from './routes/index'
import { Route as AppNotificationsImport } from './routes/app/notifications'
import { Route as AppEquipmentsImport } from './routes/app/equipments'
import { Route as AppDashboardImport } from './routes/app/dashboard'
import { Route as AppCalendarImport } from './routes/app/calendar'
import { Route as authVerifyEmailImport } from './routes/(auth)/verify-email'
import { Route as authResetPasswordImport } from './routes/(auth)/reset-password'
import { Route as authRegisterImport } from './routes/(auth)/register'
import { Route as authLoginImport } from './routes/(auth)/login'
import { Route as authForgotPasswordImport } from './routes/(auth)/forgot-password'
import { Route as AppVenuesRouteImport } from './routes/app/venues/route'
import { Route as AppUserManagementRouteImport } from './routes/app/user-management/route'
import { Route as AppSettingsRouteImport } from './routes/app/settings/route'
import { Route as AppEventsRouteImport } from './routes/app/events/route'
import { Route as AppEventStaffingRouteImport } from './routes/app/event-staffing/route'
import { Route as AppEventApprovalRouteImport } from './routes/app/event-approval/route'
import { Route as AppEquipmentApprovalRouteImport } from './routes/app/equipment-approval/route'
import { Route as AppDepartmentsRouteImport } from './routes/app/departments/route'
import { Route as AppVenuesDashboardImport } from './routes/app/venues/dashboard'
import { Route as AppVenuesVenueIdImport } from './routes/app/venues/$venueId'
import { Route as AppUserManagementUsersImport } from './routes/app/user-management/users'
import { Route as AppSettingsNotificationsImport } from './routes/app/settings/notifications'
import { Route as AppSettingsAccountImport } from './routes/app/settings/account'
import { Route as AppEventsTimelineImport } from './routes/app/events/timeline'
import { Route as AppEventsEventIdImport } from './routes/app/events/$eventId'
import { Route as AppEventStaffingStaffImport } from './routes/app/event-staffing/staff'
import { Route as AppEventApprovalApprovalImport } from './routes/app/event-approval/approval'
import { Route as AppEquipmentApprovalApprovalImport } from './routes/app/equipment-approval/approval'
import { Route as AppDepartmentsDashboardImport } from './routes/app/departments/dashboard'

// Create/Update Routes

const AppRouteRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRoute,
} as any)

const authRouteRoute = authRouteImport.update({
  id: '/(auth)',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const AppNotificationsRoute = AppNotificationsImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AppRouteRoute,
} as any)

const AppEquipmentsRoute = AppEquipmentsImport.update({
  id: '/equipments',
  path: '/equipments',
  getParentRoute: () => AppRouteRoute,
} as any)

const AppDashboardRoute = AppDashboardImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRouteRoute,
} as any)

const AppCalendarRoute = AppCalendarImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AppRouteRoute,
} as any)

const authVerifyEmailRoute = authVerifyEmailImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => authRouteRoute,
} as any)

const authResetPasswordRoute = authResetPasswordImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => authRouteRoute,
} as any)

const authRegisterRoute = authRegisterImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => authRouteRoute,
} as any)

const authLoginRoute = authLoginImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => authRouteRoute,
} as any)

const authForgotPasswordRoute = authForgotPasswordImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => authRouteRoute,
} as any)

const AppVenuesRouteRoute = AppVenuesRouteImport.update({
  id: '/venues',
  path: '/venues',
  getParentRoute: () => AppRouteRoute,
} as any)

const AppUserManagementRouteRoute = AppUserManagementRouteImport.update({
  id: '/user-management',
  path: '/user-management',
  getParentRoute: () => AppRouteRoute,
} as any)

const AppSettingsRouteRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRouteRoute,
} as any)

const AppEventsRouteRoute = AppEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => AppRouteRoute,
} as any)

const AppEventStaffingRouteRoute = AppEventStaffingRouteImport.update({
  id: '/event-staffing',
  path: '/event-staffing',
  getParentRoute: () => AppRouteRoute,
} as any)

const AppEventApprovalRouteRoute = AppEventApprovalRouteImport.update({
  id: '/event-approval',
  path: '/event-approval',
  getParentRoute: () => AppRouteRoute,
} as any)

const AppEquipmentApprovalRouteRoute = AppEquipmentApprovalRouteImport.update({
  id: '/equipment-approval',
  path: '/equipment-approval',
  getParentRoute: () => AppRouteRoute,
} as any)

const AppDepartmentsRouteRoute = AppDepartmentsRouteImport.update({
  id: '/departments',
  path: '/departments',
  getParentRoute: () => AppRouteRoute,
} as any)

const AppVenuesDashboardRoute = AppVenuesDashboardImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppVenuesRouteRoute,
} as any)

const AppVenuesVenueIdRoute = AppVenuesVenueIdImport.update({
  id: '/$venueId',
  path: '/$venueId',
  getParentRoute: () => AppVenuesRouteRoute,
} as any)

const AppUserManagementUsersRoute = AppUserManagementUsersImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AppUserManagementRouteRoute,
} as any)

const AppSettingsNotificationsRoute = AppSettingsNotificationsImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AppSettingsRouteRoute,
} as any)

const AppSettingsAccountRoute = AppSettingsAccountImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AppSettingsRouteRoute,
} as any)

const AppEventsTimelineRoute = AppEventsTimelineImport.update({
  id: '/timeline',
  path: '/timeline',
  getParentRoute: () => AppEventsRouteRoute,
} as any)

const AppEventsEventIdRoute = AppEventsEventIdImport.update({
  id: '/$eventId',
  path: '/$eventId',
  getParentRoute: () => AppEventsRouteRoute,
} as any)

const AppEventStaffingStaffRoute = AppEventStaffingStaffImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => AppEventStaffingRouteRoute,
} as any)

const AppEventApprovalApprovalRoute = AppEventApprovalApprovalImport.update({
  id: '/approval',
  path: '/approval',
  getParentRoute: () => AppEventApprovalRouteRoute,
} as any)

const AppEquipmentApprovalApprovalRoute =
  AppEquipmentApprovalApprovalImport.update({
    id: '/approval',
    path: '/approval',
    getParentRoute: () => AppEquipmentApprovalRouteRoute,
  } as any)

const AppDepartmentsDashboardRoute = AppDepartmentsDashboardImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppDepartmentsRouteRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/(auth)': {
      id: '/(auth)'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof authRouteImport
      parentRoute: typeof rootRoute
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRoute
    }
    '/app/departments': {
      id: '/app/departments'
      path: '/departments'
      fullPath: '/app/departments'
      preLoaderRoute: typeof AppDepartmentsRouteImport
      parentRoute: typeof AppRouteImport
    }
    '/app/equipment-approval': {
      id: '/app/equipment-approval'
      path: '/equipment-approval'
      fullPath: '/app/equipment-approval'
      preLoaderRoute: typeof AppEquipmentApprovalRouteImport
      parentRoute: typeof AppRouteImport
    }
    '/app/event-approval': {
      id: '/app/event-approval'
      path: '/event-approval'
      fullPath: '/app/event-approval'
      preLoaderRoute: typeof AppEventApprovalRouteImport
      parentRoute: typeof AppRouteImport
    }
    '/app/event-staffing': {
      id: '/app/event-staffing'
      path: '/event-staffing'
      fullPath: '/app/event-staffing'
      preLoaderRoute: typeof AppEventStaffingRouteImport
      parentRoute: typeof AppRouteImport
    }
    '/app/events': {
      id: '/app/events'
      path: '/events'
      fullPath: '/app/events'
      preLoaderRoute: typeof AppEventsRouteImport
      parentRoute: typeof AppRouteImport
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRouteImport
    }
    '/app/user-management': {
      id: '/app/user-management'
      path: '/user-management'
      fullPath: '/app/user-management'
      preLoaderRoute: typeof AppUserManagementRouteImport
      parentRoute: typeof AppRouteImport
    }
    '/app/venues': {
      id: '/app/venues'
      path: '/venues'
      fullPath: '/app/venues'
      preLoaderRoute: typeof AppVenuesRouteImport
      parentRoute: typeof AppRouteImport
    }
    '/(auth)/forgot-password': {
      id: '/(auth)/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof authForgotPasswordImport
      parentRoute: typeof authRouteImport
    }
    '/(auth)/login': {
      id: '/(auth)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authLoginImport
      parentRoute: typeof authRouteImport
    }
    '/(auth)/register': {
      id: '/(auth)/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof authRegisterImport
      parentRoute: typeof authRouteImport
    }
    '/(auth)/reset-password': {
      id: '/(auth)/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof authResetPasswordImport
      parentRoute: typeof authRouteImport
    }
    '/(auth)/verify-email': {
      id: '/(auth)/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof authVerifyEmailImport
      parentRoute: typeof authRouteImport
    }
    '/app/calendar': {
      id: '/app/calendar'
      path: '/calendar'
      fullPath: '/app/calendar'
      preLoaderRoute: typeof AppCalendarImport
      parentRoute: typeof AppRouteImport
    }
    '/app/dashboard': {
      id: '/app/dashboard'
      path: '/dashboard'
      fullPath: '/app/dashboard'
      preLoaderRoute: typeof AppDashboardImport
      parentRoute: typeof AppRouteImport
    }
    '/app/equipments': {
      id: '/app/equipments'
      path: '/equipments'
      fullPath: '/app/equipments'
      preLoaderRoute: typeof AppEquipmentsImport
      parentRoute: typeof AppRouteImport
    }
    '/app/notifications': {
      id: '/app/notifications'
      path: '/notifications'
      fullPath: '/app/notifications'
      preLoaderRoute: typeof AppNotificationsImport
      parentRoute: typeof AppRouteImport
    }
    '/app/departments/dashboard': {
      id: '/app/departments/dashboard'
      path: '/dashboard'
      fullPath: '/app/departments/dashboard'
      preLoaderRoute: typeof AppDepartmentsDashboardImport
      parentRoute: typeof AppDepartmentsRouteImport
    }
    '/app/equipment-approval/approval': {
      id: '/app/equipment-approval/approval'
      path: '/approval'
      fullPath: '/app/equipment-approval/approval'
      preLoaderRoute: typeof AppEquipmentApprovalApprovalImport
      parentRoute: typeof AppEquipmentApprovalRouteImport
    }
    '/app/event-approval/approval': {
      id: '/app/event-approval/approval'
      path: '/approval'
      fullPath: '/app/event-approval/approval'
      preLoaderRoute: typeof AppEventApprovalApprovalImport
      parentRoute: typeof AppEventApprovalRouteImport
    }
    '/app/event-staffing/staff': {
      id: '/app/event-staffing/staff'
      path: '/staff'
      fullPath: '/app/event-staffing/staff'
      preLoaderRoute: typeof AppEventStaffingStaffImport
      parentRoute: typeof AppEventStaffingRouteImport
    }
    '/app/events/$eventId': {
      id: '/app/events/$eventId'
      path: '/$eventId'
      fullPath: '/app/events/$eventId'
      preLoaderRoute: typeof AppEventsEventIdImport
      parentRoute: typeof AppEventsRouteImport
    }
    '/app/events/timeline': {
      id: '/app/events/timeline'
      path: '/timeline'
      fullPath: '/app/events/timeline'
      preLoaderRoute: typeof AppEventsTimelineImport
      parentRoute: typeof AppEventsRouteImport
    }
    '/app/settings/account': {
      id: '/app/settings/account'
      path: '/account'
      fullPath: '/app/settings/account'
      preLoaderRoute: typeof AppSettingsAccountImport
      parentRoute: typeof AppSettingsRouteImport
    }
    '/app/settings/notifications': {
      id: '/app/settings/notifications'
      path: '/notifications'
      fullPath: '/app/settings/notifications'
      preLoaderRoute: typeof AppSettingsNotificationsImport
      parentRoute: typeof AppSettingsRouteImport
    }
    '/app/user-management/users': {
      id: '/app/user-management/users'
      path: '/users'
      fullPath: '/app/user-management/users'
      preLoaderRoute: typeof AppUserManagementUsersImport
      parentRoute: typeof AppUserManagementRouteImport
    }
    '/app/venues/$venueId': {
      id: '/app/venues/$venueId'
      path: '/$venueId'
      fullPath: '/app/venues/$venueId'
      preLoaderRoute: typeof AppVenuesVenueIdImport
      parentRoute: typeof AppVenuesRouteImport
    }
    '/app/venues/dashboard': {
      id: '/app/venues/dashboard'
      path: '/dashboard'
      fullPath: '/app/venues/dashboard'
      preLoaderRoute: typeof AppVenuesDashboardImport
      parentRoute: typeof AppVenuesRouteImport
    }
  }
}

// Create and export the route tree

interface authRouteRouteChildren {
  authForgotPasswordRoute: typeof authForgotPasswordRoute
  authLoginRoute: typeof authLoginRoute
  authRegisterRoute: typeof authRegisterRoute
  authResetPasswordRoute: typeof authResetPasswordRoute
  authVerifyEmailRoute: typeof authVerifyEmailRoute
}

const authRouteRouteChildren: authRouteRouteChildren = {
  authForgotPasswordRoute: authForgotPasswordRoute,
  authLoginRoute: authLoginRoute,
  authRegisterRoute: authRegisterRoute,
  authResetPasswordRoute: authResetPasswordRoute,
  authVerifyEmailRoute: authVerifyEmailRoute,
}

const authRouteRouteWithChildren = authRouteRoute._addFileChildren(
  authRouteRouteChildren,
)

interface AppDepartmentsRouteRouteChildren {
  AppDepartmentsDashboardRoute: typeof AppDepartmentsDashboardRoute
}

const AppDepartmentsRouteRouteChildren: AppDepartmentsRouteRouteChildren = {
  AppDepartmentsDashboardRoute: AppDepartmentsDashboardRoute,
}

const AppDepartmentsRouteRouteWithChildren =
  AppDepartmentsRouteRoute._addFileChildren(AppDepartmentsRouteRouteChildren)

interface AppEquipmentApprovalRouteRouteChildren {
  AppEquipmentApprovalApprovalRoute: typeof AppEquipmentApprovalApprovalRoute
}

const AppEquipmentApprovalRouteRouteChildren: AppEquipmentApprovalRouteRouteChildren =
  {
    AppEquipmentApprovalApprovalRoute: AppEquipmentApprovalApprovalRoute,
  }

const AppEquipmentApprovalRouteRouteWithChildren =
  AppEquipmentApprovalRouteRoute._addFileChildren(
    AppEquipmentApprovalRouteRouteChildren,
  )

interface AppEventApprovalRouteRouteChildren {
  AppEventApprovalApprovalRoute: typeof AppEventApprovalApprovalRoute
}

const AppEventApprovalRouteRouteChildren: AppEventApprovalRouteRouteChildren = {
  AppEventApprovalApprovalRoute: AppEventApprovalApprovalRoute,
}

const AppEventApprovalRouteRouteWithChildren =
  AppEventApprovalRouteRoute._addFileChildren(
    AppEventApprovalRouteRouteChildren,
  )

interface AppEventStaffingRouteRouteChildren {
  AppEventStaffingStaffRoute: typeof AppEventStaffingStaffRoute
}

const AppEventStaffingRouteRouteChildren: AppEventStaffingRouteRouteChildren = {
  AppEventStaffingStaffRoute: AppEventStaffingStaffRoute,
}

const AppEventStaffingRouteRouteWithChildren =
  AppEventStaffingRouteRoute._addFileChildren(
    AppEventStaffingRouteRouteChildren,
  )

interface AppEventsRouteRouteChildren {
  AppEventsEventIdRoute: typeof AppEventsEventIdRoute
  AppEventsTimelineRoute: typeof AppEventsTimelineRoute
}

const AppEventsRouteRouteChildren: AppEventsRouteRouteChildren = {
  AppEventsEventIdRoute: AppEventsEventIdRoute,
  AppEventsTimelineRoute: AppEventsTimelineRoute,
}

const AppEventsRouteRouteWithChildren = AppEventsRouteRoute._addFileChildren(
  AppEventsRouteRouteChildren,
)

interface AppSettingsRouteRouteChildren {
  AppSettingsAccountRoute: typeof AppSettingsAccountRoute
  AppSettingsNotificationsRoute: typeof AppSettingsNotificationsRoute
}

const AppSettingsRouteRouteChildren: AppSettingsRouteRouteChildren = {
  AppSettingsAccountRoute: AppSettingsAccountRoute,
  AppSettingsNotificationsRoute: AppSettingsNotificationsRoute,
}

const AppSettingsRouteRouteWithChildren =
  AppSettingsRouteRoute._addFileChildren(AppSettingsRouteRouteChildren)

interface AppUserManagementRouteRouteChildren {
  AppUserManagementUsersRoute: typeof AppUserManagementUsersRoute
}

const AppUserManagementRouteRouteChildren: AppUserManagementRouteRouteChildren =
  {
    AppUserManagementUsersRoute: AppUserManagementUsersRoute,
  }

const AppUserManagementRouteRouteWithChildren =
  AppUserManagementRouteRoute._addFileChildren(
    AppUserManagementRouteRouteChildren,
  )

interface AppVenuesRouteRouteChildren {
  AppVenuesVenueIdRoute: typeof AppVenuesVenueIdRoute
  AppVenuesDashboardRoute: typeof AppVenuesDashboardRoute
}

const AppVenuesRouteRouteChildren: AppVenuesRouteRouteChildren = {
  AppVenuesVenueIdRoute: AppVenuesVenueIdRoute,
  AppVenuesDashboardRoute: AppVenuesDashboardRoute,
}

const AppVenuesRouteRouteWithChildren = AppVenuesRouteRoute._addFileChildren(
  AppVenuesRouteRouteChildren,
)

interface AppRouteRouteChildren {
  AppDepartmentsRouteRoute: typeof AppDepartmentsRouteRouteWithChildren
  AppEquipmentApprovalRouteRoute: typeof AppEquipmentApprovalRouteRouteWithChildren
  AppEventApprovalRouteRoute: typeof AppEventApprovalRouteRouteWithChildren
  AppEventStaffingRouteRoute: typeof AppEventStaffingRouteRouteWithChildren
  AppEventsRouteRoute: typeof AppEventsRouteRouteWithChildren
  AppSettingsRouteRoute: typeof AppSettingsRouteRouteWithChildren
  AppUserManagementRouteRoute: typeof AppUserManagementRouteRouteWithChildren
  AppVenuesRouteRoute: typeof AppVenuesRouteRouteWithChildren
  AppCalendarRoute: typeof AppCalendarRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppEquipmentsRoute: typeof AppEquipmentsRoute
  AppNotificationsRoute: typeof AppNotificationsRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppDepartmentsRouteRoute: AppDepartmentsRouteRouteWithChildren,
  AppEquipmentApprovalRouteRoute: AppEquipmentApprovalRouteRouteWithChildren,
  AppEventApprovalRouteRoute: AppEventApprovalRouteRouteWithChildren,
  AppEventStaffingRouteRoute: AppEventStaffingRouteRouteWithChildren,
  AppEventsRouteRoute: AppEventsRouteRouteWithChildren,
  AppSettingsRouteRoute: AppSettingsRouteRouteWithChildren,
  AppUserManagementRouteRoute: AppUserManagementRouteRouteWithChildren,
  AppVenuesRouteRoute: AppVenuesRouteRouteWithChildren,
  AppCalendarRoute: AppCalendarRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppEquipmentsRoute: AppEquipmentsRoute,
  AppNotificationsRoute: AppNotificationsRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

export interface FileRoutesByFullPath {
  '/': typeof authRouteRouteWithChildren
  '/app': typeof AppRouteRouteWithChildren
  '/app/departments': typeof AppDepartmentsRouteRouteWithChildren
  '/app/equipment-approval': typeof AppEquipmentApprovalRouteRouteWithChildren
  '/app/event-approval': typeof AppEventApprovalRouteRouteWithChildren
  '/app/event-staffing': typeof AppEventStaffingRouteRouteWithChildren
  '/app/events': typeof AppEventsRouteRouteWithChildren
  '/app/settings': typeof AppSettingsRouteRouteWithChildren
  '/app/user-management': typeof AppUserManagementRouteRouteWithChildren
  '/app/venues': typeof AppVenuesRouteRouteWithChildren
  '/forgot-password': typeof authForgotPasswordRoute
  '/login': typeof authLoginRoute
  '/register': typeof authRegisterRoute
  '/reset-password': typeof authResetPasswordRoute
  '/verify-email': typeof authVerifyEmailRoute
  '/app/calendar': typeof AppCalendarRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/equipments': typeof AppEquipmentsRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/departments/dashboard': typeof AppDepartmentsDashboardRoute
  '/app/equipment-approval/approval': typeof AppEquipmentApprovalApprovalRoute
  '/app/event-approval/approval': typeof AppEventApprovalApprovalRoute
  '/app/event-staffing/staff': typeof AppEventStaffingStaffRoute
  '/app/events/$eventId': typeof AppEventsEventIdRoute
  '/app/events/timeline': typeof AppEventsTimelineRoute
  '/app/settings/account': typeof AppSettingsAccountRoute
  '/app/settings/notifications': typeof AppSettingsNotificationsRoute
  '/app/user-management/users': typeof AppUserManagementUsersRoute
  '/app/venues/$venueId': typeof AppVenuesVenueIdRoute
  '/app/venues/dashboard': typeof AppVenuesDashboardRoute
}

export interface FileRoutesByTo {
  '/': typeof authRouteRouteWithChildren
  '/app': typeof AppRouteRouteWithChildren
  '/app/departments': typeof AppDepartmentsRouteRouteWithChildren
  '/app/equipment-approval': typeof AppEquipmentApprovalRouteRouteWithChildren
  '/app/event-approval': typeof AppEventApprovalRouteRouteWithChildren
  '/app/event-staffing': typeof AppEventStaffingRouteRouteWithChildren
  '/app/events': typeof AppEventsRouteRouteWithChildren
  '/app/settings': typeof AppSettingsRouteRouteWithChildren
  '/app/user-management': typeof AppUserManagementRouteRouteWithChildren
  '/app/venues': typeof AppVenuesRouteRouteWithChildren
  '/forgot-password': typeof authForgotPasswordRoute
  '/login': typeof authLoginRoute
  '/register': typeof authRegisterRoute
  '/reset-password': typeof authResetPasswordRoute
  '/verify-email': typeof authVerifyEmailRoute
  '/app/calendar': typeof AppCalendarRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/equipments': typeof AppEquipmentsRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/departments/dashboard': typeof AppDepartmentsDashboardRoute
  '/app/equipment-approval/approval': typeof AppEquipmentApprovalApprovalRoute
  '/app/event-approval/approval': typeof AppEventApprovalApprovalRoute
  '/app/event-staffing/staff': typeof AppEventStaffingStaffRoute
  '/app/events/$eventId': typeof AppEventsEventIdRoute
  '/app/events/timeline': typeof AppEventsTimelineRoute
  '/app/settings/account': typeof AppSettingsAccountRoute
  '/app/settings/notifications': typeof AppSettingsNotificationsRoute
  '/app/user-management/users': typeof AppUserManagementUsersRoute
  '/app/venues/$venueId': typeof AppVenuesVenueIdRoute
  '/app/venues/dashboard': typeof AppVenuesDashboardRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/(auth)': typeof authRouteRouteWithChildren
  '/app': typeof AppRouteRouteWithChildren
  '/app/departments': typeof AppDepartmentsRouteRouteWithChildren
  '/app/equipment-approval': typeof AppEquipmentApprovalRouteRouteWithChildren
  '/app/event-approval': typeof AppEventApprovalRouteRouteWithChildren
  '/app/event-staffing': typeof AppEventStaffingRouteRouteWithChildren
  '/app/events': typeof AppEventsRouteRouteWithChildren
  '/app/settings': typeof AppSettingsRouteRouteWithChildren
  '/app/user-management': typeof AppUserManagementRouteRouteWithChildren
  '/app/venues': typeof AppVenuesRouteRouteWithChildren
  '/(auth)/forgot-password': typeof authForgotPasswordRoute
  '/(auth)/login': typeof authLoginRoute
  '/(auth)/register': typeof authRegisterRoute
  '/(auth)/reset-password': typeof authResetPasswordRoute
  '/(auth)/verify-email': typeof authVerifyEmailRoute
  '/app/calendar': typeof AppCalendarRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/equipments': typeof AppEquipmentsRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/departments/dashboard': typeof AppDepartmentsDashboardRoute
  '/app/equipment-approval/approval': typeof AppEquipmentApprovalApprovalRoute
  '/app/event-approval/approval': typeof AppEventApprovalApprovalRoute
  '/app/event-staffing/staff': typeof AppEventStaffingStaffRoute
  '/app/events/$eventId': typeof AppEventsEventIdRoute
  '/app/events/timeline': typeof AppEventsTimelineRoute
  '/app/settings/account': typeof AppSettingsAccountRoute
  '/app/settings/notifications': typeof AppSettingsNotificationsRoute
  '/app/user-management/users': typeof AppUserManagementUsersRoute
  '/app/venues/$venueId': typeof AppVenuesVenueIdRoute
  '/app/venues/dashboard': typeof AppVenuesDashboardRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/app/departments'
    | '/app/equipment-approval'
    | '/app/event-approval'
    | '/app/event-staffing'
    | '/app/events'
    | '/app/settings'
    | '/app/user-management'
    | '/app/venues'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/verify-email'
    | '/app/calendar'
    | '/app/dashboard'
    | '/app/equipments'
    | '/app/notifications'
    | '/app/departments/dashboard'
    | '/app/equipment-approval/approval'
    | '/app/event-approval/approval'
    | '/app/event-staffing/staff'
    | '/app/events/$eventId'
    | '/app/events/timeline'
    | '/app/settings/account'
    | '/app/settings/notifications'
    | '/app/user-management/users'
    | '/app/venues/$venueId'
    | '/app/venues/dashboard'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/app/departments'
    | '/app/equipment-approval'
    | '/app/event-approval'
    | '/app/event-staffing'
    | '/app/events'
    | '/app/settings'
    | '/app/user-management'
    | '/app/venues'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/verify-email'
    | '/app/calendar'
    | '/app/dashboard'
    | '/app/equipments'
    | '/app/notifications'
    | '/app/departments/dashboard'
    | '/app/equipment-approval/approval'
    | '/app/event-approval/approval'
    | '/app/event-staffing/staff'
    | '/app/events/$eventId'
    | '/app/events/timeline'
    | '/app/settings/account'
    | '/app/settings/notifications'
    | '/app/user-management/users'
    | '/app/venues/$venueId'
    | '/app/venues/dashboard'
  id:
    | '__root__'
    | '/'
    | '/(auth)'
    | '/app'
    | '/app/departments'
    | '/app/equipment-approval'
    | '/app/event-approval'
    | '/app/event-staffing'
    | '/app/events'
    | '/app/settings'
    | '/app/user-management'
    | '/app/venues'
    | '/(auth)/forgot-password'
    | '/(auth)/login'
    | '/(auth)/register'
    | '/(auth)/reset-password'
    | '/(auth)/verify-email'
    | '/app/calendar'
    | '/app/dashboard'
    | '/app/equipments'
    | '/app/notifications'
    | '/app/departments/dashboard'
    | '/app/equipment-approval/approval'
    | '/app/event-approval/approval'
    | '/app/event-staffing/staff'
    | '/app/events/$eventId'
    | '/app/events/timeline'
    | '/app/settings/account'
    | '/app/settings/notifications'
    | '/app/user-management/users'
    | '/app/venues/$venueId'
    | '/app/venues/dashboard'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  authRouteRoute: typeof authRouteRouteWithChildren
  AppRouteRoute: typeof AppRouteRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  authRouteRoute: authRouteRouteWithChildren,
  AppRouteRoute: AppRouteRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/(auth)",
        "/app"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/(auth)": {
      "filePath": "(auth)/route.tsx",
      "children": [
        "/(auth)/forgot-password",
        "/(auth)/login",
        "/(auth)/register",
        "/(auth)/reset-password",
        "/(auth)/verify-email"
      ]
    },
    "/app": {
      "filePath": "app/route.tsx",
      "children": [
        "/app/departments",
        "/app/equipment-approval",
        "/app/event-approval",
        "/app/event-staffing",
        "/app/events",
        "/app/settings",
        "/app/user-management",
        "/app/venues",
        "/app/calendar",
        "/app/dashboard",
        "/app/equipments",
        "/app/notifications"
      ]
    },
    "/app/departments": {
      "filePath": "app/departments/route.tsx",
      "parent": "/app",
      "children": [
        "/app/departments/dashboard"
      ]
    },
    "/app/equipment-approval": {
      "filePath": "app/equipment-approval/route.tsx",
      "parent": "/app",
      "children": [
        "/app/equipment-approval/approval"
      ]
    },
    "/app/event-approval": {
      "filePath": "app/event-approval/route.tsx",
      "parent": "/app",
      "children": [
        "/app/event-approval/approval"
      ]
    },
    "/app/event-staffing": {
      "filePath": "app/event-staffing/route.tsx",
      "parent": "/app",
      "children": [
        "/app/event-staffing/staff"
      ]
    },
    "/app/events": {
      "filePath": "app/events/route.tsx",
      "parent": "/app",
      "children": [
        "/app/events/$eventId",
        "/app/events/timeline"
      ]
    },
    "/app/settings": {
      "filePath": "app/settings/route.tsx",
      "parent": "/app",
      "children": [
        "/app/settings/account",
        "/app/settings/notifications"
      ]
    },
    "/app/user-management": {
      "filePath": "app/user-management/route.tsx",
      "parent": "/app",
      "children": [
        "/app/user-management/users"
      ]
    },
    "/app/venues": {
      "filePath": "app/venues/route.tsx",
      "parent": "/app",
      "children": [
        "/app/venues/$venueId",
        "/app/venues/dashboard"
      ]
    },
    "/(auth)/forgot-password": {
      "filePath": "(auth)/forgot-password.tsx",
      "parent": "/(auth)"
    },
    "/(auth)/login": {
      "filePath": "(auth)/login.tsx",
      "parent": "/(auth)"
    },
    "/(auth)/register": {
      "filePath": "(auth)/register.tsx",
      "parent": "/(auth)"
    },
    "/(auth)/reset-password": {
      "filePath": "(auth)/reset-password.tsx",
      "parent": "/(auth)"
    },
    "/(auth)/verify-email": {
      "filePath": "(auth)/verify-email.tsx",
      "parent": "/(auth)"
    },
    "/app/calendar": {
      "filePath": "app/calendar.tsx",
      "parent": "/app"
    },
    "/app/dashboard": {
      "filePath": "app/dashboard.tsx",
      "parent": "/app"
    },
    "/app/equipments": {
      "filePath": "app/equipments.tsx",
      "parent": "/app"
    },
    "/app/notifications": {
      "filePath": "app/notifications.tsx",
      "parent": "/app"
    },
    "/app/departments/dashboard": {
      "filePath": "app/departments/dashboard.tsx",
      "parent": "/app/departments"
    },
    "/app/equipment-approval/approval": {
      "filePath": "app/equipment-approval/approval.tsx",
      "parent": "/app/equipment-approval"
    },
    "/app/event-approval/approval": {
      "filePath": "app/event-approval/approval.tsx",
      "parent": "/app/event-approval"
    },
    "/app/event-staffing/staff": {
      "filePath": "app/event-staffing/staff.tsx",
      "parent": "/app/event-staffing"
    },
    "/app/events/$eventId": {
      "filePath": "app/events/$eventId.tsx",
      "parent": "/app/events"
    },
    "/app/events/timeline": {
      "filePath": "app/events/timeline.tsx",
      "parent": "/app/events"
    },
    "/app/settings/account": {
      "filePath": "app/settings/account.tsx",
      "parent": "/app/settings"
    },
    "/app/settings/notifications": {
      "filePath": "app/settings/notifications.tsx",
      "parent": "/app/settings"
    },
    "/app/user-management/users": {
      "filePath": "app/user-management/users.tsx",
      "parent": "/app/user-management"
    },
    "/app/venues/$venueId": {
      "filePath": "app/venues/$venueId.tsx",
      "parent": "/app/venues"
    },
    "/app/venues/dashboard": {
      "filePath": "app/venues/dashboard.tsx",
      "parent": "/app/venues"
    }
  }
}
ROUTE_MANIFEST_END */
