/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as AppRouteImport } from './routes/app/route'
import { Route as authRouteImport } from './routes/(auth)/route'
import { Route as IndexImport } from './routes/index'
import { Route as AppNotificationsImport } from './routes/app/notifications'
import { Route as AppEquipmentsImport } from './routes/app/equipments'
import { Route as AppDashboardImport } from './routes/app/dashboard'
import { Route as AppCalendarImport } from './routes/app/calendar'
import { Route as authVerifyEmailImport } from './routes/(auth)/verify-email'
import { Route as authResetPasswordImport } from './routes/(auth)/reset-password'
import { Route as authRegisterImport } from './routes/(auth)/register'
import { Route as authLoginImport } from './routes/(auth)/login'
import { Route as authForgotPasswordImport } from './routes/(auth)/forgot-password'
import { Route as AppVenuesRouteImport } from './routes/app/venues/route'
import { Route as AppUserManagementRouteImport } from './routes/app/user-management/route'
import { Route as AppSettingsRouteImport } from './routes/app/settings/route'
import { Route as AppEventsRouteImport } from './routes/app/events/route'
import { Route as AppEventPersonnelRouteImport } from './routes/app/event-personnel/route'
import { Route as AppEventApprovalRouteImport } from './routes/app/event-approval/route'
import { Route as AppEquipmentApprovalRouteImport } from './routes/app/equipment-approval/route'
import { Route as AppDepartmentsRouteImport } from './routes/app/departments/route'
import { Route as AppVenuesIndexImport } from './routes/app/venues/index'
import { Route as AppUserManagementIndexImport } from './routes/app/user-management/index'
import { Route as AppEventsIndexImport } from './routes/app/events/index'
import { Route as AppEventPersonnelIndexImport } from './routes/app/event-personnel/index'
import { Route as AppEventApprovalIndexImport } from './routes/app/event-approval/index'
import { Route as AppEquipmentApprovalIndexImport } from './routes/app/equipment-approval/index'
import { Route as AppDepartmentsIndexImport } from './routes/app/departments/index'
import { Route as AppVenuesVenueIdImport } from './routes/app/venues/$venueId'
import { Route as AppSettingsNotificationsImport } from './routes/app/settings/notifications'
import { Route as AppSettingsAccountImport } from './routes/app/settings/account'
import { Route as AppEventsEventIdImport } from './routes/app/events/$eventId'

// Create/Update Routes

const AppRouteRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRoute,
} as any)

const authRouteRoute = authRouteImport.update({
  id: '/(auth)',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const AppNotificationsRoute = AppNotificationsImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AppRouteRoute,
} as any)

const AppEquipmentsRoute = AppEquipmentsImport.update({
  id: '/equipments',
  path: '/equipments',
  getParentRoute: () => AppRouteRoute,
} as any)

const AppDashboardRoute = AppDashboardImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRouteRoute,
} as any)

const AppCalendarRoute = AppCalendarImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AppRouteRoute,
} as any)

const authVerifyEmailRoute = authVerifyEmailImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => authRouteRoute,
} as any)

const authResetPasswordRoute = authResetPasswordImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => authRouteRoute,
} as any)

const authRegisterRoute = authRegisterImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => authRouteRoute,
} as any)

const authLoginRoute = authLoginImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => authRouteRoute,
} as any)

const authForgotPasswordRoute = authForgotPasswordImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => authRouteRoute,
} as any)

const AppVenuesRouteRoute = AppVenuesRouteImport.update({
  id: '/venues',
  path: '/venues',
  getParentRoute: () => AppRouteRoute,
} as any)

const AppUserManagementRouteRoute = AppUserManagementRouteImport.update({
  id: '/user-management',
  path: '/user-management',
  getParentRoute: () => AppRouteRoute,
} as any)

const AppSettingsRouteRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRouteRoute,
} as any)

const AppEventsRouteRoute = AppEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => AppRouteRoute,
} as any)

const AppEventPersonnelRouteRoute = AppEventPersonnelRouteImport.update({
  id: '/event-personnel',
  path: '/event-personnel',
  getParentRoute: () => AppRouteRoute,
} as any)

const AppEventApprovalRouteRoute = AppEventApprovalRouteImport.update({
  id: '/event-approval',
  path: '/event-approval',
  getParentRoute: () => AppRouteRoute,
} as any)

const AppEquipmentApprovalRouteRoute = AppEquipmentApprovalRouteImport.update({
  id: '/equipment-approval',
  path: '/equipment-approval',
  getParentRoute: () => AppRouteRoute,
} as any)

const AppDepartmentsRouteRoute = AppDepartmentsRouteImport.update({
  id: '/departments',
  path: '/departments',
  getParentRoute: () => AppRouteRoute,
} as any)

const AppVenuesIndexRoute = AppVenuesIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppVenuesRouteRoute,
} as any)

const AppUserManagementIndexRoute = AppUserManagementIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppUserManagementRouteRoute,
} as any)

const AppEventsIndexRoute = AppEventsIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppEventsRouteRoute,
} as any)

const AppEventPersonnelIndexRoute = AppEventPersonnelIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppEventPersonnelRouteRoute,
} as any)

const AppEventApprovalIndexRoute = AppEventApprovalIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppEventApprovalRouteRoute,
} as any)

const AppEquipmentApprovalIndexRoute = AppEquipmentApprovalIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppEquipmentApprovalRouteRoute,
} as any)

const AppDepartmentsIndexRoute = AppDepartmentsIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppDepartmentsRouteRoute,
} as any)

const AppVenuesVenueIdRoute = AppVenuesVenueIdImport.update({
  id: '/$venueId',
  path: '/$venueId',
  getParentRoute: () => AppVenuesRouteRoute,
} as any)

const AppSettingsNotificationsRoute = AppSettingsNotificationsImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AppSettingsRouteRoute,
} as any)

const AppSettingsAccountRoute = AppSettingsAccountImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AppSettingsRouteRoute,
} as any)

const AppEventsEventIdRoute = AppEventsEventIdImport.update({
  id: '/$eventId',
  path: '/$eventId',
  getParentRoute: () => AppEventsRouteRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/(auth)': {
      id: '/(auth)'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof authRouteImport
      parentRoute: typeof rootRoute
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRoute
    }
    '/app/departments': {
      id: '/app/departments'
      path: '/departments'
      fullPath: '/app/departments'
      preLoaderRoute: typeof AppDepartmentsRouteImport
      parentRoute: typeof AppRouteImport
    }
    '/app/equipment-approval': {
      id: '/app/equipment-approval'
      path: '/equipment-approval'
      fullPath: '/app/equipment-approval'
      preLoaderRoute: typeof AppEquipmentApprovalRouteImport
      parentRoute: typeof AppRouteImport
    }
    '/app/event-approval': {
      id: '/app/event-approval'
      path: '/event-approval'
      fullPath: '/app/event-approval'
      preLoaderRoute: typeof AppEventApprovalRouteImport
      parentRoute: typeof AppRouteImport
    }
    '/app/event-personnel': {
      id: '/app/event-personnel'
      path: '/event-personnel'
      fullPath: '/app/event-personnel'
      preLoaderRoute: typeof AppEventPersonnelRouteImport
      parentRoute: typeof AppRouteImport
    }
    '/app/events': {
      id: '/app/events'
      path: '/events'
      fullPath: '/app/events'
      preLoaderRoute: typeof AppEventsRouteImport
      parentRoute: typeof AppRouteImport
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRouteImport
    }
    '/app/user-management': {
      id: '/app/user-management'
      path: '/user-management'
      fullPath: '/app/user-management'
      preLoaderRoute: typeof AppUserManagementRouteImport
      parentRoute: typeof AppRouteImport
    }
    '/app/venues': {
      id: '/app/venues'
      path: '/venues'
      fullPath: '/app/venues'
      preLoaderRoute: typeof AppVenuesRouteImport
      parentRoute: typeof AppRouteImport
    }
    '/(auth)/forgot-password': {
      id: '/(auth)/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof authForgotPasswordImport
      parentRoute: typeof authRouteImport
    }
    '/(auth)/login': {
      id: '/(auth)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authLoginImport
      parentRoute: typeof authRouteImport
    }
    '/(auth)/register': {
      id: '/(auth)/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof authRegisterImport
      parentRoute: typeof authRouteImport
    }
    '/(auth)/reset-password': {
      id: '/(auth)/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof authResetPasswordImport
      parentRoute: typeof authRouteImport
    }
    '/(auth)/verify-email': {
      id: '/(auth)/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof authVerifyEmailImport
      parentRoute: typeof authRouteImport
    }
    '/app/calendar': {
      id: '/app/calendar'
      path: '/calendar'
      fullPath: '/app/calendar'
      preLoaderRoute: typeof AppCalendarImport
      parentRoute: typeof AppRouteImport
    }
    '/app/dashboard': {
      id: '/app/dashboard'
      path: '/dashboard'
      fullPath: '/app/dashboard'
      preLoaderRoute: typeof AppDashboardImport
      parentRoute: typeof AppRouteImport
    }
    '/app/equipments': {
      id: '/app/equipments'
      path: '/equipments'
      fullPath: '/app/equipments'
      preLoaderRoute: typeof AppEquipmentsImport
      parentRoute: typeof AppRouteImport
    }
    '/app/notifications': {
      id: '/app/notifications'
      path: '/notifications'
      fullPath: '/app/notifications'
      preLoaderRoute: typeof AppNotificationsImport
      parentRoute: typeof AppRouteImport
    }
    '/app/events/$eventId': {
      id: '/app/events/$eventId'
      path: '/$eventId'
      fullPath: '/app/events/$eventId'
      preLoaderRoute: typeof AppEventsEventIdImport
      parentRoute: typeof AppEventsRouteImport
    }
    '/app/settings/account': {
      id: '/app/settings/account'
      path: '/account'
      fullPath: '/app/settings/account'
      preLoaderRoute: typeof AppSettingsAccountImport
      parentRoute: typeof AppSettingsRouteImport
    }
    '/app/settings/notifications': {
      id: '/app/settings/notifications'
      path: '/notifications'
      fullPath: '/app/settings/notifications'
      preLoaderRoute: typeof AppSettingsNotificationsImport
      parentRoute: typeof AppSettingsRouteImport
    }
    '/app/venues/$venueId': {
      id: '/app/venues/$venueId'
      path: '/$venueId'
      fullPath: '/app/venues/$venueId'
      preLoaderRoute: typeof AppVenuesVenueIdImport
      parentRoute: typeof AppVenuesRouteImport
    }
    '/app/departments/': {
      id: '/app/departments/'
      path: '/'
      fullPath: '/app/departments/'
      preLoaderRoute: typeof AppDepartmentsIndexImport
      parentRoute: typeof AppDepartmentsRouteImport
    }
    '/app/equipment-approval/': {
      id: '/app/equipment-approval/'
      path: '/'
      fullPath: '/app/equipment-approval/'
      preLoaderRoute: typeof AppEquipmentApprovalIndexImport
      parentRoute: typeof AppEquipmentApprovalRouteImport
    }
    '/app/event-approval/': {
      id: '/app/event-approval/'
      path: '/'
      fullPath: '/app/event-approval/'
      preLoaderRoute: typeof AppEventApprovalIndexImport
      parentRoute: typeof AppEventApprovalRouteImport
    }
    '/app/event-personnel/': {
      id: '/app/event-personnel/'
      path: '/'
      fullPath: '/app/event-personnel/'
      preLoaderRoute: typeof AppEventPersonnelIndexImport
      parentRoute: typeof AppEventPersonnelRouteImport
    }
    '/app/events/': {
      id: '/app/events/'
      path: '/'
      fullPath: '/app/events/'
      preLoaderRoute: typeof AppEventsIndexImport
      parentRoute: typeof AppEventsRouteImport
    }
    '/app/user-management/': {
      id: '/app/user-management/'
      path: '/'
      fullPath: '/app/user-management/'
      preLoaderRoute: typeof AppUserManagementIndexImport
      parentRoute: typeof AppUserManagementRouteImport
    }
    '/app/venues/': {
      id: '/app/venues/'
      path: '/'
      fullPath: '/app/venues/'
      preLoaderRoute: typeof AppVenuesIndexImport
      parentRoute: typeof AppVenuesRouteImport
    }
  }
}

// Create and export the route tree

interface authRouteRouteChildren {
  authForgotPasswordRoute: typeof authForgotPasswordRoute
  authLoginRoute: typeof authLoginRoute
  authRegisterRoute: typeof authRegisterRoute
  authResetPasswordRoute: typeof authResetPasswordRoute
  authVerifyEmailRoute: typeof authVerifyEmailRoute
}

const authRouteRouteChildren: authRouteRouteChildren = {
  authForgotPasswordRoute: authForgotPasswordRoute,
  authLoginRoute: authLoginRoute,
  authRegisterRoute: authRegisterRoute,
  authResetPasswordRoute: authResetPasswordRoute,
  authVerifyEmailRoute: authVerifyEmailRoute,
}

const authRouteRouteWithChildren = authRouteRoute._addFileChildren(
  authRouteRouteChildren,
)

interface AppDepartmentsRouteRouteChildren {
  AppDepartmentsIndexRoute: typeof AppDepartmentsIndexRoute
}

const AppDepartmentsRouteRouteChildren: AppDepartmentsRouteRouteChildren = {
  AppDepartmentsIndexRoute: AppDepartmentsIndexRoute,
}

const AppDepartmentsRouteRouteWithChildren =
  AppDepartmentsRouteRoute._addFileChildren(AppDepartmentsRouteRouteChildren)

interface AppEquipmentApprovalRouteRouteChildren {
  AppEquipmentApprovalIndexRoute: typeof AppEquipmentApprovalIndexRoute
}

const AppEquipmentApprovalRouteRouteChildren: AppEquipmentApprovalRouteRouteChildren =
  {
    AppEquipmentApprovalIndexRoute: AppEquipmentApprovalIndexRoute,
  }

const AppEquipmentApprovalRouteRouteWithChildren =
  AppEquipmentApprovalRouteRoute._addFileChildren(
    AppEquipmentApprovalRouteRouteChildren,
  )

interface AppEventApprovalRouteRouteChildren {
  AppEventApprovalIndexRoute: typeof AppEventApprovalIndexRoute
}

const AppEventApprovalRouteRouteChildren: AppEventApprovalRouteRouteChildren = {
  AppEventApprovalIndexRoute: AppEventApprovalIndexRoute,
}

const AppEventApprovalRouteRouteWithChildren =
  AppEventApprovalRouteRoute._addFileChildren(
    AppEventApprovalRouteRouteChildren,
  )

interface AppEventPersonnelRouteRouteChildren {
  AppEventPersonnelIndexRoute: typeof AppEventPersonnelIndexRoute
}

const AppEventPersonnelRouteRouteChildren: AppEventPersonnelRouteRouteChildren =
  {
    AppEventPersonnelIndexRoute: AppEventPersonnelIndexRoute,
  }

const AppEventPersonnelRouteRouteWithChildren =
  AppEventPersonnelRouteRoute._addFileChildren(
    AppEventPersonnelRouteRouteChildren,
  )

interface AppEventsRouteRouteChildren {
  AppEventsEventIdRoute: typeof AppEventsEventIdRoute
  AppEventsIndexRoute: typeof AppEventsIndexRoute
}

const AppEventsRouteRouteChildren: AppEventsRouteRouteChildren = {
  AppEventsEventIdRoute: AppEventsEventIdRoute,
  AppEventsIndexRoute: AppEventsIndexRoute,
}

const AppEventsRouteRouteWithChildren = AppEventsRouteRoute._addFileChildren(
  AppEventsRouteRouteChildren,
)

interface AppSettingsRouteRouteChildren {
  AppSettingsAccountRoute: typeof AppSettingsAccountRoute
  AppSettingsNotificationsRoute: typeof AppSettingsNotificationsRoute
}

const AppSettingsRouteRouteChildren: AppSettingsRouteRouteChildren = {
  AppSettingsAccountRoute: AppSettingsAccountRoute,
  AppSettingsNotificationsRoute: AppSettingsNotificationsRoute,
}

const AppSettingsRouteRouteWithChildren =
  AppSettingsRouteRoute._addFileChildren(AppSettingsRouteRouteChildren)

interface AppUserManagementRouteRouteChildren {
  AppUserManagementIndexRoute: typeof AppUserManagementIndexRoute
}

const AppUserManagementRouteRouteChildren: AppUserManagementRouteRouteChildren =
  {
    AppUserManagementIndexRoute: AppUserManagementIndexRoute,
  }

const AppUserManagementRouteRouteWithChildren =
  AppUserManagementRouteRoute._addFileChildren(
    AppUserManagementRouteRouteChildren,
  )

interface AppVenuesRouteRouteChildren {
  AppVenuesVenueIdRoute: typeof AppVenuesVenueIdRoute
  AppVenuesIndexRoute: typeof AppVenuesIndexRoute
}

const AppVenuesRouteRouteChildren: AppVenuesRouteRouteChildren = {
  AppVenuesVenueIdRoute: AppVenuesVenueIdRoute,
  AppVenuesIndexRoute: AppVenuesIndexRoute,
}

const AppVenuesRouteRouteWithChildren = AppVenuesRouteRoute._addFileChildren(
  AppVenuesRouteRouteChildren,
)

interface AppRouteRouteChildren {
  AppDepartmentsRouteRoute: typeof AppDepartmentsRouteRouteWithChildren
  AppEquipmentApprovalRouteRoute: typeof AppEquipmentApprovalRouteRouteWithChildren
  AppEventApprovalRouteRoute: typeof AppEventApprovalRouteRouteWithChildren
  AppEventPersonnelRouteRoute: typeof AppEventPersonnelRouteRouteWithChildren
  AppEventsRouteRoute: typeof AppEventsRouteRouteWithChildren
  AppSettingsRouteRoute: typeof AppSettingsRouteRouteWithChildren
  AppUserManagementRouteRoute: typeof AppUserManagementRouteRouteWithChildren
  AppVenuesRouteRoute: typeof AppVenuesRouteRouteWithChildren
  AppCalendarRoute: typeof AppCalendarRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppEquipmentsRoute: typeof AppEquipmentsRoute
  AppNotificationsRoute: typeof AppNotificationsRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppDepartmentsRouteRoute: AppDepartmentsRouteRouteWithChildren,
  AppEquipmentApprovalRouteRoute: AppEquipmentApprovalRouteRouteWithChildren,
  AppEventApprovalRouteRoute: AppEventApprovalRouteRouteWithChildren,
  AppEventPersonnelRouteRoute: AppEventPersonnelRouteRouteWithChildren,
  AppEventsRouteRoute: AppEventsRouteRouteWithChildren,
  AppSettingsRouteRoute: AppSettingsRouteRouteWithChildren,
  AppUserManagementRouteRoute: AppUserManagementRouteRouteWithChildren,
  AppVenuesRouteRoute: AppVenuesRouteRouteWithChildren,
  AppCalendarRoute: AppCalendarRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppEquipmentsRoute: AppEquipmentsRoute,
  AppNotificationsRoute: AppNotificationsRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

export interface FileRoutesByFullPath {
  '/': typeof authRouteRouteWithChildren
  '/app': typeof AppRouteRouteWithChildren
  '/app/departments': typeof AppDepartmentsRouteRouteWithChildren
  '/app/equipment-approval': typeof AppEquipmentApprovalRouteRouteWithChildren
  '/app/event-approval': typeof AppEventApprovalRouteRouteWithChildren
  '/app/event-personnel': typeof AppEventPersonnelRouteRouteWithChildren
  '/app/events': typeof AppEventsRouteRouteWithChildren
  '/app/settings': typeof AppSettingsRouteRouteWithChildren
  '/app/user-management': typeof AppUserManagementRouteRouteWithChildren
  '/app/venues': typeof AppVenuesRouteRouteWithChildren
  '/forgot-password': typeof authForgotPasswordRoute
  '/login': typeof authLoginRoute
  '/register': typeof authRegisterRoute
  '/reset-password': typeof authResetPasswordRoute
  '/verify-email': typeof authVerifyEmailRoute
  '/app/calendar': typeof AppCalendarRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/equipments': typeof AppEquipmentsRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/events/$eventId': typeof AppEventsEventIdRoute
  '/app/settings/account': typeof AppSettingsAccountRoute
  '/app/settings/notifications': typeof AppSettingsNotificationsRoute
  '/app/venues/$venueId': typeof AppVenuesVenueIdRoute
  '/app/departments/': typeof AppDepartmentsIndexRoute
  '/app/equipment-approval/': typeof AppEquipmentApprovalIndexRoute
  '/app/event-approval/': typeof AppEventApprovalIndexRoute
  '/app/event-personnel/': typeof AppEventPersonnelIndexRoute
  '/app/events/': typeof AppEventsIndexRoute
  '/app/user-management/': typeof AppUserManagementIndexRoute
  '/app/venues/': typeof AppVenuesIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof authRouteRouteWithChildren
  '/app': typeof AppRouteRouteWithChildren
  '/app/settings': typeof AppSettingsRouteRouteWithChildren
  '/forgot-password': typeof authForgotPasswordRoute
  '/login': typeof authLoginRoute
  '/register': typeof authRegisterRoute
  '/reset-password': typeof authResetPasswordRoute
  '/verify-email': typeof authVerifyEmailRoute
  '/app/calendar': typeof AppCalendarRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/equipments': typeof AppEquipmentsRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/events/$eventId': typeof AppEventsEventIdRoute
  '/app/settings/account': typeof AppSettingsAccountRoute
  '/app/settings/notifications': typeof AppSettingsNotificationsRoute
  '/app/venues/$venueId': typeof AppVenuesVenueIdRoute
  '/app/departments': typeof AppDepartmentsIndexRoute
  '/app/equipment-approval': typeof AppEquipmentApprovalIndexRoute
  '/app/event-approval': typeof AppEventApprovalIndexRoute
  '/app/event-personnel': typeof AppEventPersonnelIndexRoute
  '/app/events': typeof AppEventsIndexRoute
  '/app/user-management': typeof AppUserManagementIndexRoute
  '/app/venues': typeof AppVenuesIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/(auth)': typeof authRouteRouteWithChildren
  '/app': typeof AppRouteRouteWithChildren
  '/app/departments': typeof AppDepartmentsRouteRouteWithChildren
  '/app/equipment-approval': typeof AppEquipmentApprovalRouteRouteWithChildren
  '/app/event-approval': typeof AppEventApprovalRouteRouteWithChildren
  '/app/event-personnel': typeof AppEventPersonnelRouteRouteWithChildren
  '/app/events': typeof AppEventsRouteRouteWithChildren
  '/app/settings': typeof AppSettingsRouteRouteWithChildren
  '/app/user-management': typeof AppUserManagementRouteRouteWithChildren
  '/app/venues': typeof AppVenuesRouteRouteWithChildren
  '/(auth)/forgot-password': typeof authForgotPasswordRoute
  '/(auth)/login': typeof authLoginRoute
  '/(auth)/register': typeof authRegisterRoute
  '/(auth)/reset-password': typeof authResetPasswordRoute
  '/(auth)/verify-email': typeof authVerifyEmailRoute
  '/app/calendar': typeof AppCalendarRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/equipments': typeof AppEquipmentsRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/events/$eventId': typeof AppEventsEventIdRoute
  '/app/settings/account': typeof AppSettingsAccountRoute
  '/app/settings/notifications': typeof AppSettingsNotificationsRoute
  '/app/venues/$venueId': typeof AppVenuesVenueIdRoute
  '/app/departments/': typeof AppDepartmentsIndexRoute
  '/app/equipment-approval/': typeof AppEquipmentApprovalIndexRoute
  '/app/event-approval/': typeof AppEventApprovalIndexRoute
  '/app/event-personnel/': typeof AppEventPersonnelIndexRoute
  '/app/events/': typeof AppEventsIndexRoute
  '/app/user-management/': typeof AppUserManagementIndexRoute
  '/app/venues/': typeof AppVenuesIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/app/departments'
    | '/app/equipment-approval'
    | '/app/event-approval'
    | '/app/event-personnel'
    | '/app/events'
    | '/app/settings'
    | '/app/user-management'
    | '/app/venues'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/verify-email'
    | '/app/calendar'
    | '/app/dashboard'
    | '/app/equipments'
    | '/app/notifications'
    | '/app/events/$eventId'
    | '/app/settings/account'
    | '/app/settings/notifications'
    | '/app/venues/$venueId'
    | '/app/departments/'
    | '/app/equipment-approval/'
    | '/app/event-approval/'
    | '/app/event-personnel/'
    | '/app/events/'
    | '/app/user-management/'
    | '/app/venues/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/app/settings'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/verify-email'
    | '/app/calendar'
    | '/app/dashboard'
    | '/app/equipments'
    | '/app/notifications'
    | '/app/events/$eventId'
    | '/app/settings/account'
    | '/app/settings/notifications'
    | '/app/venues/$venueId'
    | '/app/departments'
    | '/app/equipment-approval'
    | '/app/event-approval'
    | '/app/event-personnel'
    | '/app/events'
    | '/app/user-management'
    | '/app/venues'
  id:
    | '__root__'
    | '/'
    | '/(auth)'
    | '/app'
    | '/app/departments'
    | '/app/equipment-approval'
    | '/app/event-approval'
    | '/app/event-personnel'
    | '/app/events'
    | '/app/settings'
    | '/app/user-management'
    | '/app/venues'
    | '/(auth)/forgot-password'
    | '/(auth)/login'
    | '/(auth)/register'
    | '/(auth)/reset-password'
    | '/(auth)/verify-email'
    | '/app/calendar'
    | '/app/dashboard'
    | '/app/equipments'
    | '/app/notifications'
    | '/app/events/$eventId'
    | '/app/settings/account'
    | '/app/settings/notifications'
    | '/app/venues/$venueId'
    | '/app/departments/'
    | '/app/equipment-approval/'
    | '/app/event-approval/'
    | '/app/event-personnel/'
    | '/app/events/'
    | '/app/user-management/'
    | '/app/venues/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  authRouteRoute: typeof authRouteRouteWithChildren
  AppRouteRoute: typeof AppRouteRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  authRouteRoute: authRouteRouteWithChildren,
  AppRouteRoute: AppRouteRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/(auth)",
        "/app"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/(auth)": {
      "filePath": "(auth)/route.tsx",
      "children": [
        "/(auth)/forgot-password",
        "/(auth)/login",
        "/(auth)/register",
        "/(auth)/reset-password",
        "/(auth)/verify-email"
      ]
    },
    "/app": {
      "filePath": "app/route.tsx",
      "children": [
        "/app/departments",
        "/app/equipment-approval",
        "/app/event-approval",
        "/app/event-personnel",
        "/app/events",
        "/app/settings",
        "/app/user-management",
        "/app/venues",
        "/app/calendar",
        "/app/dashboard",
        "/app/equipments",
        "/app/notifications"
      ]
    },
    "/app/departments": {
      "filePath": "app/departments/route.tsx",
      "parent": "/app",
      "children": [
        "/app/departments/"
      ]
    },
    "/app/equipment-approval": {
      "filePath": "app/equipment-approval/route.tsx",
      "parent": "/app",
      "children": [
        "/app/equipment-approval/"
      ]
    },
    "/app/event-approval": {
      "filePath": "app/event-approval/route.tsx",
      "parent": "/app",
      "children": [
        "/app/event-approval/"
      ]
    },
    "/app/event-personnel": {
      "filePath": "app/event-personnel/route.tsx",
      "parent": "/app",
      "children": [
        "/app/event-personnel/"
      ]
    },
    "/app/events": {
      "filePath": "app/events/route.tsx",
      "parent": "/app",
      "children": [
        "/app/events/$eventId",
        "/app/events/"
      ]
    },
    "/app/settings": {
      "filePath": "app/settings/route.tsx",
      "parent": "/app",
      "children": [
        "/app/settings/account",
        "/app/settings/notifications"
      ]
    },
    "/app/user-management": {
      "filePath": "app/user-management/route.tsx",
      "parent": "/app",
      "children": [
        "/app/user-management/"
      ]
    },
    "/app/venues": {
      "filePath": "app/venues/route.tsx",
      "parent": "/app",
      "children": [
        "/app/venues/$venueId",
        "/app/venues/"
      ]
    },
    "/(auth)/forgot-password": {
      "filePath": "(auth)/forgot-password.tsx",
      "parent": "/(auth)"
    },
    "/(auth)/login": {
      "filePath": "(auth)/login.tsx",
      "parent": "/(auth)"
    },
    "/(auth)/register": {
      "filePath": "(auth)/register.tsx",
      "parent": "/(auth)"
    },
    "/(auth)/reset-password": {
      "filePath": "(auth)/reset-password.tsx",
      "parent": "/(auth)"
    },
    "/(auth)/verify-email": {
      "filePath": "(auth)/verify-email.tsx",
      "parent": "/(auth)"
    },
    "/app/calendar": {
      "filePath": "app/calendar.tsx",
      "parent": "/app"
    },
    "/app/dashboard": {
      "filePath": "app/dashboard.tsx",
      "parent": "/app"
    },
    "/app/equipments": {
      "filePath": "app/equipments.tsx",
      "parent": "/app"
    },
    "/app/notifications": {
      "filePath": "app/notifications.tsx",
      "parent": "/app"
    },
    "/app/events/$eventId": {
      "filePath": "app/events/$eventId.tsx",
      "parent": "/app/events"
    },
    "/app/settings/account": {
      "filePath": "app/settings/account.tsx",
      "parent": "/app/settings"
    },
    "/app/settings/notifications": {
      "filePath": "app/settings/notifications.tsx",
      "parent": "/app/settings"
    },
    "/app/venues/$venueId": {
      "filePath": "app/venues/$venueId.tsx",
      "parent": "/app/venues"
    },
    "/app/departments/": {
      "filePath": "app/departments/index.tsx",
      "parent": "/app/departments"
    },
    "/app/equipment-approval/": {
      "filePath": "app/equipment-approval/index.tsx",
      "parent": "/app/equipment-approval"
    },
    "/app/event-approval/": {
      "filePath": "app/event-approval/index.tsx",
      "parent": "/app/event-approval"
    },
    "/app/event-personnel/": {
      "filePath": "app/event-personnel/index.tsx",
      "parent": "/app/event-personnel"
    },
    "/app/events/": {
      "filePath": "app/events/index.tsx",
      "parent": "/app/events"
    },
    "/app/user-management/": {
      "filePath": "app/user-management/index.tsx",
      "parent": "/app/user-management"
    },
    "/app/venues/": {
      "filePath": "app/venues/index.tsx",
      "parent": "/app/venues"
    }
  }
}
ROUTE_MANIFEST_END */
